version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "pip install -r misc/requirements.txt && python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata:
