# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 04:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.IntegerField()),
                ('breed', models.CharField(choices=[('angus', 'Angus'), ('red_angus', 'Red Angus'), ('simmental', 'Simmental'), ('simangus', 'SimAngus'), ('shorthorn', 'Shorthorn'), ('charolais', 'Charolais'), ('hereford', 'Hereford'), ('brahman', 'Brahman'), ('brangus', 'Brangus'), ('limousin', 'Limousin'), ('limflex', 'LimFlex')], max_length=25)),
                ('sex', models.CharField(choices=[('b', 'Bull'), ('f', 'Female')], max_length=25)),
                ('female_type', models.CharField(blank=True, choices=[('cow', 'Cow'), ('replacement_heifer', 'Replacement Heifer'), ('bred_heifer', 'Bred Heifer'), ('pair', 'Pair')], max_length=25, null=True)),
                ('registration_number', models.CharField(max_length=25)),
                ('bull_name', models.CharField(max_length=55)),
                ('sire', models.CharField(max_length=55)),
                ('dame', models.CharField(max_length=55)),
                ('scrotal_circumference', models.DecimalField(decimal_places=2, max_digits=3)),
                ('birth_weight', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weaning_weight', models.IntegerField()),
                ('yearling_weight', models.IntegerField()),
                ('residual_average_daily_gain', models.DecimalField(decimal_places=2, max_digits=2)),
                ('heifer_pregnancy', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calving_ease_maternal', models.IntegerField()),
                ('maternal_milk', models.IntegerField()),
                ('mature_weight', models.IntegerField()),
                ('mature_height', models.DecimalField(decimal_places=1, max_digits=2)),
                ('cow_energy_value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('carcass_weight', models.IntegerField()),
                ('marbling', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ribeye_area', models.DecimalField(decimal_places=2, max_digits=3)),
                ('fat_thickness', models.DecimalField(decimal_places=3, max_digits=3)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
