# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0002_auto_20160810_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattle',
            name='sex',
            field=models.CharField(choices=[('bull', 'Bull'), ('female', 'Female')], max_length=25),
        ),
    ]
