# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattle',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2016, 8, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cattle',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.date(2016, 8, 19)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cattle',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='original_image',
            field=models.ImageField(upload_to='cattle_images/'),
        ),
    ]
