# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-02 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cattle', '0005_auto_20160819_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cattle',
            unique_together=set([('producer', 'bull_name')]),
        ),
    ]
