# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='newsletter',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip',
            field=localflavor.us.models.USZipCodeField(blank=True, null=True),
        ),
    ]
